controller:
  enable: true
  replicas: 2  # HA Mode
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "local-path"

  service: ClusterIP

  database:
    type: "postgres"
    url: "jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/database"
    user: "omer-test"
    password: "omer-test"
    database: "omer-test"

  admin:
    existingSecret: jenkins-admin-secret
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
